# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: JÄ™drzej Michalczyk blog
email: jedrzej.michalczyk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
            Personal blog about Problem based thinking.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: JedrzejQ
github_username:  jedrzejmichalczyk

# Build settings
markdown: kramdown

plugins: 
  - jekyll-org
theme: jekyll-theme-minimal